/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-11-20 01:44:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import util.dbhelper.DBconn;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class MAIN_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, webkit\">\n");
      out.write("<title>Untitled Document</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/calendar.css\">\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("        \n");
      out.write("\t\thtml {\n");
      out.write("            font: 500 10px \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        a {\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        ul,\n");
      out.write("        ol,\n");
      out.write("        li {\n");
      out.write("            list-style: none;\n");
      out.write("            padding: 0;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #demo {\n");
      out.write("            width: 300px;\n");
      out.write("            margin: 30px auto;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        p {\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        input {\n");
      out.write("            margin: 30px auto;\n");
      out.write("            height: 28px;\n");
      out.write("            width: 200px;\n");
      out.write("            padding: 0 6px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\t\t\n");
      out.write("\t\t#STATICMENU { margin: 2.5pt; padding: 0pt;  position:absolute; right: 8%; top: 85%; height:30pt; width:23px;'}\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("<script src=\"js/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"js/calendar.js\"></script>\n");
      out.write("\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("<![endif]-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body style=\"background-color:#FAF8EE\">\n");
      out.write("<nav class=\"navbar navbar-inverse\" style=\"border-color:#FAF8EE; background-color:#FAF8EE\">\n");
      out.write("  <div class=\"container-fluid\" style=\"background-color:#FAF8EE\">\n");
      out.write("    <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("    <div class=\"navbar-header\" style=\"background-color: #69bd8d; border-color: #69bd8d;\" >\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#inverseNavbar1\" style=\"border-color:#fff; background-color:#69bd8d; column-rule-color:#69bd8d;\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button>\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\" style=\"color:#fff; font-size:24px; text-align:center; margin-left:20px\" onClick=\"location='MAIN.html'\">전김강정조</a></div>\n");
      out.write("    <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"inverseNavbar1\" align=\"center\" style=\"background-color: #69BD8D; border-color: #FAF8EE; margin-top: -6px;\">\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\" style=\"border-color: #FAF8EE; color: #69bd8d; margin-bottom: 12px;\">\n");
      out.write("      <div class=\"btn-group\" role=\"group\">\n");
      out.write("      <button type=\"button\" class=\"alert-info\" style=\"margin-right:5px\">속도UP</button>\n");
      out.write("      <button type=\"button\" class=\"alert-warning\" style=\"margin-left:5px\" onClick=\"location='SETTING.html'\">설정하기</button>\n");
      out.write("      <button type=\"button\" class=\"alert-success\" style=\"margin-left:5px; background-color:#e9e4f0; border-color:#b9b5bf; color:#7129d3\" onClick=\"location='ORDERED.html'\">배송보기</button>\n");
      out.write("       </div>\n");
      out.write("      </ul>\n");
      out.write("</div><br>\n");
      out.write("    <div align=\"center\">\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" style=\"margin-bottom:5px; width:260px\" onClick=\"location='ORDER.jsp'\">주문 하기</button><br>\n");
      out.write("    <button type=\"button\" class=\"btn btn-info\" style=\"margin-bottom:5px; width:260px\">왔던 주문</button><br>\n");
      out.write("    <button type=\"button\" class=\"btn btn-success\" style=\"margin-bottom:5px; width:260px\">했던 주문</button><br>\n");
      out.write("    <button type=\"button\" class=\"btn btn-warning\" style=\"margin-bottom:15px; width:260px\">내 정보들</button><br>\n");
      out.write("    </div>\n");
      out.write("<div class=\"wall\" align=\"center\">\n");
      out.write("  <div id=\"ca\"></div>\n");
      out.write("    <script src=\"calendar.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        var now = new Date();\n");
      out.write("        var year = now.getFullYear();\n");
      out.write("        var month = now.getMonth()+1 ;\n");
      out.write("        var date = now.getDate();\n");
      out.write("\n");
      out.write("\n");
      out.write("        var data = [ ];\n");
      out.write("\n");
      out.write("        // inline\n");
      out.write("        var $ca = $('#ca').calendar({\n");
      out.write("            // view: 'month',\n");
      out.write("            width: 260,\n");
      out.write("            height: 260,\n");
      out.write("            // startWeek: 0,\n");
      out.write("            // selectedRang: [new Date(), null],\n");
      out.write("            data: data,\n");
      out.write("            date: new Date(),\n");
      out.write("            onSelected: function(view, date, data) {\n");
      out.write("                console.log('view:' + view)\n");
      out.write("                console.log('date:' + date)\n");
      out.write("                console.log('data:' + (data || '无'));\n");
      out.write("            },\n");
      out.write("            viewChange: function(view, y, m) {\n");
      out.write("                console.log(view, y, m)\n");
      out.write("\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // picker\n");
      out.write("        $('#dd').calendar({\n");
      out.write("            trigger: '#dt',\n");
      out.write("            // offset: [0, 1],\n");
      out.write("            zIndex: 999,\n");
      out.write("            data: data,\n");
      out.write("            onSelected: function(view, date, data) {\n");
      out.write("                console.log('event: onSelected')\n");
      out.write("            },\n");
      out.write("            onClose: function(view, date, data) {\n");
      out.write("                console.log('event: onClose')\n");
      out.write("                console.log('view:' + view)\n");
      out.write("                console.log('date:' + date)\n");
      out.write("                console.log('data:' + (data || '无'));\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <script language=\"javascript\"> </script>\n");
      out.write("</div>\n");
      out.write("    <!-- /.navbar-collapse -->\n");
      out.write("<form id=\"STATICMENU\" style=\"background:none; z-index:2\">\n");
      out.write("<img src=\"icon/console.png\" width=\"35\" height=\"55\" onclick=\"click_test()\" alt=\"\"/>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write(" var stmnLEFT = 10; // 오른쪽 여백 \n");
      out.write(" var stmnGAP1 = 0; // 위쪽 여백 \n");
      out.write(" var stmnGAP2 = 150; // 스크롤시 브라우저 위쪽과 떨어지는 거리 \n");
      out.write(" var stmnBASE = 150; // 스크롤 시작위치 \n");
      out.write(" var stmnActivateSpeed = 35; //스크롤을 인식하는 딜레이 (숫자가 클수록 느리게 인식)\n");
      out.write(" var stmnScrollSpeed = 20; //스크롤 속도 (클수록 느림)\n");
      out.write(" var stmnTimer; \n");
      out.write(" var flag = 0;\n");
      out.write(" \n");
      out.write(" function RefreshStaticMenu() { \n");
      out.write("  var stmnStartPoint, stmnEndPoint; \n");
      out.write("  stmnStartPoint = parseInt(document.getElementById('STATICMENU').style.top, 10); \n");
      out.write("  stmnEndPoint = Math.max(document.documentElement.scrollTop, document.body.scrollTop) + stmnGAP2; \n");
      out.write("  if (stmnEndPoint < stmnGAP1) stmnEndPoint = stmnGAP1; \n");
      out.write("  if (stmnStartPoint != stmnEndPoint) { \n");
      out.write("   stmnScrollAmount = Math.ceil( Math.abs( stmnEndPoint - stmnStartPoint ) / 15 ); \n");
      out.write("   document.getElementById('STATICMENU').style.top = parseInt(document.getElementById('STATICMENU').style.top, 10) + ( ( stmnEndPoint<stmnStartPoint ) ? -stmnScrollAmount : stmnScrollAmount ) + 'px'; \n");
      out.write("   stmnRefreshTimer = stmnScrollSpeed; \n");
      out.write("   }\n");
      out.write("  stmnTimer = setTimeout(\"RefreshStaticMenu();\", stmnActivateSpeed); \n");
      out.write("  } \n");
      out.write(" function InitializeStaticMenu() {\n");
      out.write(" // document.getElementById('STATICMENU').style.backgroundColor=\"#dde8f0\"; //크기 보고 싶어서 색 바꿔 놓음 #dde8f0\n");
      out.write("  document.getElementById('STATICMENU').style.right = stmnLEFT + 'px';  //처음에 오른쪽에 위치. left로 바꿔도.\n");
      out.write("  document.getElementById('STATICMENU').style.top = document.body.scrollTop + stmnBASE + 'px'; \n");
      out.write("  //document.getElementById('STATICMENU').style.backgroundImage = url(icon/test.png);\n");
      out.write("  RefreshStaticMenu();\n");
      out.write("  }\n");
      out.write(" \n");
      out.write(" function click_test(){\n");
      out.write("\tvar obj = document.getElementById('STATICMENU');\n");
      out.write("\t \n");
      out.write("\tif(flag == 0)\n");
      out.write("\t{\n");
      out.write("\t\t\n");
      out.write("\t\tvar btnupdate = document.createElement('img');\n");
      out.write("\t    btnupdate.setAttribute('id', 'b1');\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/lace.png');\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right : 0px; bottom :90px ; height:25pt; width:25px; solid : #0000');\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test1');  };\n");
      out.write("\t    obj.appendChild(btnupdate);\n");
      out.write("\t    \n");
      out.write("\t    var btnupdate = document.createElement('img');\n");
      out.write("\t    btnupdate.setAttribute('id', 'b2');\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/credit-card.png');\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right : 33px; bottom :99px ; height:23pt; width:30px; solid : #0000')\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test');  };\n");
      out.write("\t    obj.appendChild(btnupdate);\n");
      out.write("\t\t\n");
      out.write("\t\t var btnupdate = document.createElement('img');\n");
      out.write("\t    btnupdate.setAttribute('id', 'b3');\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/delivery-truck.png');\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right :35px; bottom:95px ; height:25pt; width:30px; solid : #0000')\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test');  };\n");
      out.write("\t    obj.appendChild(btnupdate); \n");
      out.write("\t    \n");
      out.write("\t    var btnupdate = document.createElement('img');\n");
      out.write("\t    btnupdate.setAttribute('id', 'b4');\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/fix.png');\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right :15px; bottom : 96px ; height:25pt; width:25px; solid : #0000')\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test');  };\n");
      out.write("\t    obj.appendChild(btnupdate);\n");
      out.write("\t    \n");
      out.write("\t    flag = 1;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\telse if(flag == 1)\n");
      out.write("\t{\n");
      out.write("\t\tvar btn = document.getElementById(\"b1\");\n");
      out.write("\t\tobj.removeChild(btn);\n");
      out.write("\t\t\n");
      out.write("\t\tvar btn = document.getElementById(\"b2\");\n");
      out.write("\t\tobj.removeChild(btn);\n");
      out.write("\t\t\n");
      out.write("\t\tvar btn = document.getElementById(\"b3\");\n");
      out.write("\t\tobj.removeChild(btn);\n");
      out.write("\t\t\n");
      out.write("\t\tvar btn = document.getElementById(\"b4\");\n");
      out.write("\t\tobj.removeChild(btn);\n");
      out.write("\t\t\n");
      out.write("\t\tflag = 0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write(" }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  <!-- /.container-fluid -->\n");
      out.write("</nav>\n");
      out.write("<footer class=\"footer\" id=\"footer\" align=\"right\" style=\"color:#8ba0e8; margin-right:10px\">Three J Two K company</footer>\n");
      out.write("<script src=\"js/bootstrap.js\" type=\"text/javascript\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
