/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-11-19 09:34:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import util.dbhelper.DBconn;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class ORDER_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("      \r\n");
      out.write("\t\t#STATICMENU { margin: 2.5pt; padding: 0pt;  position:absolute; right: 8%; top: 85%; height:30pt; width:23px;'}\r\n");
      out.write("    </style>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color:#FAF8EE\">\r\n");
      out.write("<nav class=\"navbar navbar-inverse\" style=\"border-color:#FAF8EE; background-color:#FAF8EE\">\r\n");
      out.write("  <div class=\"container-fluid\" style=\"background-color:#FAF8EE\">\r\n");
      out.write("    <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("    <div class=\"navbar-header\" style=\"background-color: #69bd8d; border-color: #69bd8d;\" >\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#inverseNavbar1\" style=\"border-color:#fff; background-color:#69bd8d; column-rule-color:#69bd8d;\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\" style=\"color:#fff; font-size:24px; text-align:center; margin-left:20px; margin-top:-3px\" onClick=\"location='MAIN.html'\"><span class=\"glyphicon glyphicon-home\" aria-hidden=\"true\" style=\"margin-right:-10px\">&nbsp;</span>홈으로...</a></div>\r\n");
      out.write("    <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"inverseNavbar1\" align=\"center\" style=\"background-color: #69BD8D; border-color: #FAF8EE; margin-top: -6px;\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\" style=\"border-color: #FAF8EE; color: #69bd8d; margin-bottom: 12px;\">\r\n");
      out.write("      <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("      <button type=\"button\" class=\"alert-info\" style=\"margin-right:5px\">속도UP</button>\r\n");
      out.write("      <button type=\"button\" class=\"alert-warning\" style=\"margin-left:5px\" onClick=\"location='SETTING.html'\">설정하기</button>\r\n");
      out.write("      <button type=\"button\" class=\"alert-success\" style=\"margin-left:5px; background-color:#e9e4f0; border-color:#b9b5bf; color:#7129d3\" onClick=\"location='SETTING.html'\">배송보기</button>\r\n");
      out.write("       </div>\r\n");
      out.write("      </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("    <!-- /.navbar-collapse -->\r\n");
      out.write("    \r\n");
      out.write("     <div align=\"center\">\r\n");
      out.write("    <input type=\"search\"/>\r\n");
      out.write("    <strong>\r\n");
      out.write("    <button class=\"btn\" style=\"color:#8A6C3B; background-color:#FAF8EE; font-size:20px\" onClick=\"location='ITEM_INFO.html'\">검색하기</button>\r\n");
      out.write("    </strong><br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <span style=\"text-align:center\">\r\n");
      out.write("    <button class=\"glyphicon glyphicon-star\" aria-hidden=\"true\" style=\"color:#FFD500; background-color:#FAF8EE; border:hidden; width:10%; text-align:center\" onClick=\"location='FAVORITE.html'\"></button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-info\" draggable=\"true\" style=\"width:30%; text-align:center\">1</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-success\" draggable=\"true\" style=\"width:20%; text-align:center\">2</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-warning\" draggable=\"true\" style=\"width:10%; text-align:center\">3</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-ss\" style=\"color:#2140B7; background-color:#FAF8EE; width:10%; text-align:center\" onClick=\"location='FAVplus.jsp'\">+</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-ss\" style=\"color:#CA2222; background-color:#FAF8EE; width:10%; text-align:center\" onClick=\"location='FAVminus.jsp'\">-</button>\r\n");
      out.write("    </span>\r\n");
      out.write("  <!------- ---->\r\n");
      out.write("  <hr>\r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("    <input type=\"search\"/><strong>\r\n");
      out.write("    <button class=\"btn\" style=\"color:#8A6C3B; background-color:#FAF8EE; font-size:20px; margin-bottom:8px\" onClick=\"location='ACCEPT_1.html'\">주문하기</button></strong><br>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div id =\"Shopping_Cart\" style=\"width:100%; height:320px; overflow:auto\" align=\"center\">\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("<!------ TABLE SORTING javascript -- start -->    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function sortingNumber( a , b ){  \r\n");
      out.write("\r\n");
      out.write("        if ( typeof a == \"number\" && typeof b == \"number\" ) return a - b; \r\n");
      out.write("\r\n");
      out.write("        // 천단위 쉼표와 공백문자만 삭제하기.  \r\n");
      out.write("        var a = ( a + \"\" ).replace( /[,\\s\\xA0]+/g , \"\" ); \r\n");
      out.write("        var b = ( b + \"\" ).replace( /[,\\s\\xA0]+/g , \"\" ); \r\n");
      out.write("\r\n");
      out.write("        var numA = parseFloat( a ) + \"\"; \r\n");
      out.write("        var numB = parseFloat( b ) + \"\"; \r\n");
      out.write("\r\n");
      out.write("        if ( numA == \"NaN\" || numB == \"NaN\" || a != numA || b != numB ) return false; \r\n");
      out.write("\r\n");
      out.write("        return parseFloat( a ) - parseFloat( b ); \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* changeForSorting() : 문자열 바꾸기. */ \r\n");
      out.write("\r\n");
      out.write("function changeForSorting( first , second ){  \r\n");
      out.write("\r\n");
      out.write("        // 문자열의 복사본 만들기. \r\n");
      out.write("        var a = first.toString().replace( /[\\s\\xA0]+/g , \" \" ); \r\n");
      out.write("        var b = second.toString().replace( /[\\s\\xA0]+/g , \" \" ); \r\n");
      out.write("\r\n");
      out.write("        var change = { first : a, second : b }; \r\n");
      out.write("\r\n");
      out.write("        if ( a.search( /\\d/ ) < 0 || b.search( /\\d/ ) < 0 || a.length == 0 || b.length == 0 ) return change; \r\n");
      out.write("\r\n");
      out.write("        var regExp = /(\\d),(\\d)/g; // 천단위 쉼표를 찾기 위한 정규식. \r\n");
      out.write("\r\n");
      out.write("        a = a.replace( regExp , \"$1\" + \"$2\" ); \r\n");
      out.write("        b = b.replace( regExp , \"$1\" + \"$2\" ); \r\n");
      out.write("\r\n");
      out.write("        var unit = 0; \r\n");
      out.write("        var aNb = a + \" \" + b; \r\n");
      out.write("        var numbers = aNb.match( /\\d+/g ); // 문자열에 들어있는 숫자 찾기 \r\n");
      out.write("\r\n");
      out.write("        for ( var x = 0; x < numbers.length; x++ ){ \r\n");
      out.write("\r\n");
      out.write("                var length = numbers[ x ].length; \r\n");
      out.write("                if ( unit < length ) unit = length; \r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        var addZero = function( string ){ // 숫자들의 단위 맞추기 \r\n");
      out.write("\r\n");
      out.write("                var match = string.match( /^0+/ ); \r\n");
      out.write("\r\n");
      out.write("                if ( string.length == unit ) return ( match == null ) ? string : match + string; \r\n");
      out.write("\r\n");
      out.write("                var zero = \"0\"; \r\n");
      out.write("\r\n");
      out.write("                for ( var x = string.length; x < unit; x++ ) string = zero + string; \r\n");
      out.write("\r\n");
      out.write("                return ( match == null ) ? string : match + string; \r\n");
      out.write("        }; \r\n");
      out.write("\r\n");
      out.write("        change.first = a.replace( /\\d+/g, addZero ); \r\n");
      out.write("        change.second = b.replace( /\\d+/g, addZero ); \r\n");
      out.write("\r\n");
      out.write("        return change; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* byLocale() */ \r\n");
      out.write("\r\n");
      out.write("function byLocale(){ \r\n");
      out.write("\r\n");
      out.write("        var compare = function( a , b ){ \r\n");
      out.write("\r\n");
      out.write("                var sorting = sortingNumber( a , b ); \r\n");
      out.write("\r\n");
      out.write("                if ( typeof sorting == \"number\" ) return sorting; \r\n");
      out.write("\r\n");
      out.write("                var change = changeForSorting( a , b ); \r\n");
      out.write("\r\n");
      out.write("                var a = change.first; \r\n");
      out.write("                var b = change.second; \r\n");
      out.write("\r\n");
      out.write("                return a.localeCompare( b ); \r\n");
      out.write("        }; \r\n");
      out.write("\r\n");
      out.write("        var ascendingOrder = function( a , b ){  return compare( a , b );  }; \r\n");
      out.write("        var descendingOrder = function( a , b ){  return compare( b , a );  }; \r\n");
      out.write("\r\n");
      out.write("        return { ascending : ascendingOrder, descending : descendingOrder }; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* replacement() */ \r\n");
      out.write(" \r\n");
      out.write("function replacement( parent ){  \r\n");
      out.write("        var tagName = parent.tagName.toLowerCase(); \r\n");
      out.write("        if ( tagName == \"table\" ) parent = parent.tBodies[ 0 ]; \r\n");
      out.write("        tagName = parent.tagName.toLowerCase(); \r\n");
      out.write("        if ( tagName == \"tbody\" ) var children = parent.rows; \r\n");
      out.write("        else var children = parent.getElementsByTagName( \"li\" ); \r\n");
      out.write("\r\n");
      out.write("        var replace = { \r\n");
      out.write("                order : byLocale(), \r\n");
      out.write("                index : false, \r\n");
      out.write("                array : function(){ \r\n");
      out.write("                        var array = [ ]; \r\n");
      out.write("                        for ( var x = 0; x < children.length; x++ ) array[ x ] = children[ x ]; \r\n");
      out.write("                        return array; \r\n");
      out.write("                }(), \r\n");
      out.write("                checkIndex : function( index ){ \r\n");
      out.write("                        if ( index ) this.index = parseInt( index, 10 ); \r\n");
      out.write("                        var tagName = parent.tagName.toLowerCase(); \r\n");
      out.write("                        if ( tagName == \"tbody\" && ! index ) this.index = 0; \r\n");
      out.write("                }, \r\n");
      out.write("                getText : function( child ){ \r\n");
      out.write("                        if ( this.index ) child = child.cells[ this.index ]; \r\n");
      out.write("                        return getTextByClone( child ); \r\n");
      out.write("                }, \r\n");
      out.write("                setChildren : function(){ \r\n");
      out.write("                        var array = this.array; \r\n");
      out.write("                        while ( parent.hasChildNodes() ) parent.removeChild( parent.firstChild ); \r\n");
      out.write("                        for ( var x = 0; x < array.length; x++ ) parent.appendChild( array[ x ] ); \r\n");
      out.write("                }, \r\n");
      out.write("                ascending : function( index ){ // 오름차순 \r\n");
      out.write("                        this.checkIndex( index ); \r\n");
      out.write("                        var _self = this; \r\n");
      out.write("                        var order = this.order; \r\n");
      out.write("                        var ascending = function( a, b ){ \r\n");
      out.write("                                var a = _self.getText( a ); \r\n");
      out.write("                                var b = _self.getText( b ); \r\n");
      out.write("                                return order.ascending( a, b ); \r\n");
      out.write("                        }; \r\n");
      out.write("                        this.array.sort( ascending ); \r\n");
      out.write("                        this.setChildren(); \r\n");
      out.write("                }, \r\n");
      out.write("                descending : function( index ){ // 내림차순\r\n");
      out.write("                        this.checkIndex( index ); \r\n");
      out.write("                        var _self = this; \r\n");
      out.write("                        var order = this.order; \r\n");
      out.write("                        var descending = function( a, b ){ \r\n");
      out.write("                                var a = _self.getText( a ); \r\n");
      out.write("                                var b = _self.getText( b ); \r\n");
      out.write("                                return order.descending( a, b ); \r\n");
      out.write("                        }; \r\n");
      out.write("                        this.array.sort( descending ); \r\n");
      out.write("                        this.setChildren(); \r\n");
      out.write("                } \r\n");
      out.write("        }; \r\n");
      out.write("        return replace; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("function getTextByClone( tag ){  \r\n");
      out.write("        var clone = tag.cloneNode( true ); // 태그의 복사본 만들기. \r\n");
      out.write("        var br = clone.getElementsByTagName( \"br\" ); \r\n");
      out.write("        while ( br[0] ){ \r\n");
      out.write("                var blank = document.createTextNode( \" \" ); \r\n");
      out.write("                clone.insertBefore( blank , br[0] ); \r\n");
      out.write("                clone.removeChild( br[0] ); \r\n");
      out.write("        } \r\n");
      out.write("        var isBlock = function( tag ){ \r\n");
      out.write("                var display = \"\"; \r\n");
      out.write("                if ( window.getComputedStyle ) display = window.getComputedStyle ( tag, \"\" )[ \"display\" ]; \r\n");
      out.write("                else display = tag.currentStyle[ \"display\" ]; \r\n");
      out.write("                return ( display == \"block\" ) ? true : false; \r\n");
      out.write("        }; \r\n");
      out.write("        var children = clone.getElementsByTagName( \"*\" ); \r\n");
      out.write("        for ( var x = 0; x < children.length; x++){ \r\n");
      out.write("                var child = children[ x ]; \r\n");
      out.write("                if ( ! (\"value\" in child) && isBlock(child) ) child.innerHTML = child.innerHTML + \" \"; \r\n");
      out.write("        } \r\n");
      out.write("        var textContent = clone.textContent || clone.innerText; \r\n");
      out.write("        return textContent; \r\n");
      out.write("} \r\n");
      out.write("</script>\r\n");
      out.write("  <!------ TABLE SORTING javascript -- end -->    \r\n");
      out.write("  \r\n");
      out.write("  <table id=\"cart\" class=\"sortable\" width=\"100%\" border=\"0\">\r\n");
      out.write("  \t<thead>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("        <th class=\"check\" style=\"text-align:center\">상태<button class=\"btn\" style=\"background-color:#FAF8EE; font-size:10px; width:4px; padding-left:0px\" onclick=\"sortTD (0)\">▲</button><button class=\"btn\" onclick=\"reverseTD (0)\" style=\"background-color:#FAF8EE; font-size: 10px; width: 4px; padding-left: 0px;\">▼</button></th>\r\n");
      out.write("            <th class=\"name\" style=\"text-align:center\">이름<button class=\"btn\" onclick=\"sortTD(1)\" style=\"background-color:#FAF8EE; font-size:10px; width:4px; padding-left:0px\">▲</button><button class=\"btn\" style=\"background-color:#FAF8EE; font-size:10px; width:4px; padding-left:0px\" onclick=\"reverseTD(1)\">▼</button></th>\r\n");
      out.write("             <th  class=\"company\" style=\"text-align:center\">회사<button class=\"btn\" style=\"background-color:#FAF8EE; font-size:10px; width:4px; padding-left:0px\" onclick=\"sortTD(2)\">▲</button><button class=\"btn\" style=\"background-color:#FAF8EE; font-size:10px; width:4px; padding-left:0px\"  onclick=\"reverseTD(2)\">▼</button></th>\r\n");
      out.write("\t\t\t <th class=\"number\" style=\"text-align:center\">갯수<button class=\"btn\" style=\"background-color:#FAF8EE; font-size:10px; width:4px; padding-left:0px\" onclick=\"sortTD(3)\">▲</button><button class=\"btn\" style=\"background-color:#FAF8EE; font-size:10px; width:4px; padding-left:0px\"  onclick=\"reverseTD(3)\">▼</button></th>\r\n");
      out.write("         </tr>\r\n");
      out.write("     </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">감</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">삼성앨쥐</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">애플짜응</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">치킨</td>\r\n");
      out.write("      <td style=\"text-align:center\">통큐</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\" style=\"text-align:center\"><input type=\"checkbox\"></th>\r\n");
      out.write("      <td style=\"text-align:center\">커피</td>\r\n");
      out.write("      <td style=\"text-align:center\">하바나</td>\r\n");
      out.write("      <td style=\"text-align:center\"><input type=\"number\" style=\"width:60px\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("    <!------- ------->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.container-fluid -->\r\n");
      out.write("</nav>\r\n");
      out.write("<form id=\"STATICMENU\" style=\"background:none\">\r\n");
      out.write("<img src=\"icon/console.png\" width=\"35\" height=\"55\" onclick=\"click_test()\" alt=\"\"/>\r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" var stmnLEFT = 10; // 오른쪽 여백 \r\n");
      out.write(" var stmnGAP1 = 0; // 위쪽 여백 \r\n");
      out.write(" var stmnGAP2 = 150; // 스크롤시 브라우저 위쪽과 떨어지는 거리 \r\n");
      out.write(" var stmnBASE = 150; // 스크롤 시작위치 \r\n");
      out.write(" var stmnActivateSpeed = 35; //스크롤을 인식하는 딜레이 (숫자가 클수록 느리게 인식)\r\n");
      out.write(" var stmnScrollSpeed = 20; //스크롤 속도 (클수록 느림)\r\n");
      out.write(" var stmnTimer; \r\n");
      out.write(" var flag = 0;\r\n");
      out.write(" \r\n");
      out.write(" function RefreshStaticMenu() { \r\n");
      out.write("  var stmnStartPoint, stmnEndPoint; \r\n");
      out.write("  stmnStartPoint = parseInt(document.getElementById('STATICMENU').style.top, 10); \r\n");
      out.write("  stmnEndPoint = Math.max(document.documentElement.scrollTop, document.body.scrollTop) + stmnGAP2; \r\n");
      out.write("  if (stmnEndPoint < stmnGAP1) stmnEndPoint = stmnGAP1; \r\n");
      out.write("  if (stmnStartPoint != stmnEndPoint) { \r\n");
      out.write("   stmnScrollAmount = Math.ceil( Math.abs( stmnEndPoint - stmnStartPoint ) / 15 ); \r\n");
      out.write("   document.getElementById('STATICMENU').style.top = parseInt(document.getElementById('STATICMENU').style.top, 10) + ( ( stmnEndPoint<stmnStartPoint ) ? -stmnScrollAmount : stmnScrollAmount ) + 'px'; \r\n");
      out.write("   stmnRefreshTimer = stmnScrollSpeed; \r\n");
      out.write("   }\r\n");
      out.write("  stmnTimer = setTimeout(\"RefreshStaticMenu();\", stmnActivateSpeed); \r\n");
      out.write("  } \r\n");
      out.write(" function InitializeStaticMenu() {\r\n");
      out.write(" // document.getElementById('STATICMENU').style.backgroundColor=\"#dde8f0\"; //크기 보고 싶어서 색 바꿔 놓음 #dde8f0\r\n");
      out.write("  \r\n");
      out.write("  document.getElementById('STATICMENU').style.right = stmnLEFT + 'px';  //처음에 오른쪽에 위치. left로 바꿔도.\r\n");
      out.write("  document.getElementById('STATICMENU').style.top = document.body.scrollTop + stmnBASE + 'px'; \r\n");
      out.write("  //document.getElementById('STATICMENU').style.backgroundImage = url(icon/test.png);\r\n");
      out.write("  RefreshStaticMenu();\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write(" function click_test(){\r\n");
      out.write("\tvar obj = document.getElementById('STATICMENU');\r\n");
      out.write("\t \r\n");
      out.write("\tif(flag == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar btnupdate = document.createElement('img');\r\n");
      out.write("\t    btnupdate.setAttribute('id', 'b1');\r\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\r\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/lace.png');\r\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right : 0px; bottom :90px ; height:25pt; width:25px; solid : #0000');\r\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test1');  };\r\n");
      out.write("\t    obj.appendChild(btnupdate);\r\n");
      out.write("\t    \r\n");
      out.write("\t    var btnupdate = document.createElement('img');\r\n");
      out.write("\t    btnupdate.setAttribute('id', 'b2');\r\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\r\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/credit-card.png');\r\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right : 33px; bottom :99px ; height:23pt; width:30px; solid : #0000')\r\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test');  };\r\n");
      out.write("\t    obj.appendChild(btnupdate);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t var btnupdate = document.createElement('img');\r\n");
      out.write("\t    btnupdate.setAttribute('id', 'b3');\r\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\r\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/delivery-truck.png');\r\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right :35px; bottom:95px ; height:25pt; width:30px; solid : #0000')\r\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test');  };\r\n");
      out.write("\t    obj.appendChild(btnupdate); \r\n");
      out.write("\t    \r\n");
      out.write("\t    var btnupdate = document.createElement('img');\r\n");
      out.write("\t    btnupdate.setAttribute('id', 'b4');\r\n");
      out.write("\t    //btnupdate.setAttribute('type', 'button');\r\n");
      out.write("\t    btnupdate.setAttribute('src', 'icon/fix.png');\r\n");
      out.write("\t    btnupdate.setAttribute('style','position :relative; right :15px; bottom : 96px ; height:25pt; width:25px; solid : #0000')\r\n");
      out.write("\t    btnupdate.onclick = function() {  alert('test');  };\r\n");
      out.write("\t    obj.appendChild(btnupdate);\r\n");
      out.write("\t    \r\n");
      out.write("\t    flag = 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\telse if(flag == 1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar btn = document.getElementById(\"b1\");\r\n");
      out.write("\t\tobj.removeChild(btn);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar btn = document.getElementById(\"b2\");\r\n");
      out.write("\t\tobj.removeChild(btn);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar btn = document.getElementById(\"b3\");\r\n");
      out.write("\t\tobj.removeChild(btn);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar btn = document.getElementById(\"b4\");\r\n");
      out.write("\t\tobj.removeChild(btn);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tflag = 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer\" id=\"footer\" align=\"right\" style=\"color:#8ba0e8; margin-right:10px\">Three J Two K company</footer>\r\n");
      out.write("<script src=\"js/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var myTable = document.getElementById( \"cart\" ); \r\n");
      out.write("var replace = replacement( myTable ); \r\n");
      out.write("function sortTD( index ){    replace.ascending( index );    } \r\n");
      out.write("function reverseTD( index ){    replace.descending( index );    } \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>>>\r\n");
      out.write("\r\n");

	int count = 0;
	int Total_size = 0;
	int Array_count[] = new int[0];
	int Array_id[] = new int[0];
	String Array_name[] = new String[0];
	int i = 0;
	request.setCharacterEncoding("UTF-8");
	String code = request.getParameter("code");
	Connection conn = DBconn.getConnection();
	

	int item_count = 0;
	
	//메인에서 order 들어왔을 때

		Statement st = conn.createStatement();

		String sql = "Select bookmark_id,bookmark_name,weight from bookmark order by weight DESC";
		ResultSet rs = st.executeQuery(sql);
		Array_count = new int[3];
		Array_name = new String[3];
		Array_id = new int[3];
		while (rs.next()) {
			
			int Bookmark_id = rs.getInt("bookmark_id");
			int Bookmark_count = rs.getInt("weight");
			String Bookmark_name = rs.getString("bookmark_name");
			Array_id[i] = Bookmark_id;
			Array_name[i] = Bookmark_name;
			Array_count[i] = Bookmark_count;
			Total_size += Bookmark_count;
			i++;
			if (i == 3)
				break;
		}

		rs.close();
		st.close();
		DBconn.close();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t// 그리는거 \r\n");
      out.write("\t\tvar count = 3;\r\n");
      out.write("\t\tvar ary_count = new Array();\r\n");
      out.write("\t\tvar ary_name = new Array();\r\n");
      out.write("\t\tvar ary_id = new Array();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
for (int k = 0; k < 3; k++) {
      out.write("\r\n");
      out.write("\t\t\tary_id[");
      out.print(k);
      out.write("] = '");
      out.print(Array_id[k]);
      out.write("';\r\n");
      out.write("\t\t\tary_name[");
      out.print(k);
      out.write("] = '");
      out.print(Array_name[k]);
      out.write("';\r\n");
}
      out.write("\r\n");
      out.write("\telm = document.getElementById(\"favorite_button_span\");\r\n");
      out.write("\tvar form = document.createElement('form');\r\n");
      out.write("\tform.setAttribute(\"method\", \"POST\");\r\n");
      out.write("\tform.setAttribute(\"action\",\"FAVORITE.jsp\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar button_add_fav = document.createElement('button');\r\n");
      out.write("\r\n");
      out.write("\tbutton_add_fav.setAttribute(\"style\",\"border:hidden; color:#FFFFFF; background-color:rgba(255,155,156,1.0); border-color:rgba(230,155,156,1.00)\");\r\n");
      out.write("\tbutton_add_fav.setAttribute(\"class\",\"glyphicon glyphicon-star\");\r\n");
      out.write("\tbutton_add_fav.setAttribute(\"onClick\",\"location = 'FAVORITE.jsp'\");\r\n");
      out.write("\t\r\n");
      out.write("\tform.appendChild(button_add_fav);\r\n");
      out.write("\telm.appendChild(form);\r\n");
      out.write("\t\r\n");
      out.write(" \tvar form2 = document.createElement('form');\r\n");
      out.write(" \tform2.setAttribute(\"method\",\"POST\");\r\n");
      out.write(" \tform2.setAttribute(\"action\",\"ORDER.jsp\");\r\n");
      out.write(" \telm.appendChild(form2);\r\n");
      out.write("\tfor (var n = 0; n < count; n++) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar input_element = document.createElement('input');\r\n");
      out.write("\t\tinput_element.setAttribute(\"type\", \"submit\");\r\n");
      out.write("\t\tinput_element.setAttribute(\"name\", \"bookmark_id\");\r\n");
      out.write("\t\tinput_element.setAttribute(\"value\", ary_id[n]);\r\n");
      out.write("\t\tinput_element.style.width = \"10%\";\r\n");
      out.write("\t\tswitch (n) {\r\n");
      out.write("\t\tcase 0:\r\n");
      out.write("\t\t\tinput_element.setAttribute(\"class\", \"btn btn-info\");\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 1:\r\n");
      out.write("\t\t\tinput_element.setAttribute(\"class\", \"btn btn-success\");\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 2:\r\n");
      out.write("\t\t\tinput_element.setAttribute(\"class\", \"btn btn-warning\");\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tdefault:\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tform2.appendChild(input_element);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\telm2 = document.getElementId('favorite_button_span2');\r\n");
      out.write("\t\r\n");
      out.write("\tvar plus_form = document.createElement('form');\r\n");
      out.write("\tplus_form.setAttribute(\"method\",\"POST\");\r\n");
      out.write("\tplus_form.setAttribute(\"action\",\"FAVplus.jsp\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar plus_input = document.createElement('input');\r\n");
      out.write("\tplus_input.setAttribute(\"type\", \"submit\");\r\n");
      out.write("\tplus_input.setAttribute(\"name\", \"submit\");\r\n");
      out.write("\tplus_input.setAttribute(\"value\", \"+\");\r\n");
      out.write("\tplus_form.appendChild(plus_input);\r\n");
      out.write("\telm.appendChild(plus_form);\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar minus_form = document.createElement('form');\r\n");
      out.write("\tminus_form.setAttribute(\"method\",\"POST\");\r\n");
      out.write("\tminus_form.setAttribute(\"action\",\"FAVminus.html\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar minus_input = document.createElement('input');\r\n");
      out.write("\tminus_input.setAttribute(\"type\", \"submit\");\r\n");
      out.write("\tminus_input.setAttribute(\"name\", \"submit\");\r\n");
      out.write("\tminus_input.setAttribute(\"value\", \"-\");\r\n");
      out.write("\tminus_form.appendChild(minus_input);\r\n");
      out.write("\telm.appendChild(minus_form);\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  여기가 즐겨찾기 눌렀을 때 cart에 추가해주는 곳  -->\r\n");

	conn = DBconn.getConnection();
	st = null;
	sql = null;
	rs = null;
	Array_id = new int[0];
	Array_count = new int[0];
	int Array_price[] = new int[0];
	String bookmark_id = request.getParameter("bookmark_id");
	
	if(bookmark_id != null)
	{
		st = conn.createStatement();
		
		sql = "select count(*) as count "+
		"from favorite "+
				"where bookmark_id="+bookmark_id;
		
		rs = st.executeQuery(sql);
		if(rs.next()){
			count = rs.getInt("count");
		}
		Array_id = new int[count];
		Array_count = new int[count];
		Array_name = new String[count];
		Array_price = new int[count];
		
		st = conn.createStatement();
		sql = "select item_id, count "+
				"from favorite "+
						"where bookmark_id="+bookmark_id;
		
		rs = st.executeQuery(sql);
		i = 0;
		while(rs.next())
		{
			Array_id[i] = rs.getInt("item_id");
			Array_count[i] = rs.getInt("count");
			i++;
		}
		st.close();
		
		if(count > 0){
			st = conn.createStatement();
			sql = "select name, price "+
				"from item "+
					"where ";
			for(i = 0 ; i < count; i++)
			{
				sql += "id="+Array_id[i];
				if(i == count-1)
					break;
				sql += " or ";
			}
			System.out.println(sql);
			rs = st.executeQuery(sql);
			i = 0;
			while(rs.next())
			{
				Array_name[i] = rs.getString("name");
				Array_price[i] = rs.getInt("price");
				i++;
			}
		}
		for(i = 0; i < count; i++)
		{
			st = conn.createStatement();
			
			sql = "insert into cart values("+Array_id[i]+","+Array_count[i]+")";
			st.executeUpdate(sql);
			
		}
		
		
		st.close();
		
	
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar ary_name = new Array();\r\n");
      out.write("\tvar ary_count = new Array();\r\n");
      out.write("\tvar ary_price = new Array();\r\n");
      out.write("\tvar count = \"");
      out.print(count);
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\t");
for (int k = 0; k < count; k++) {
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tary_count[");
      out.print(k);
      out.write("] = '");
      out.print(Array_count[k]);
      out.write("';\r\n");
      out.write("\tary_name[");
      out.print(k);
      out.write("] = '");
      out.print(Array_name[k]);
      out.write("';\r\n");
      out.write("\tary_price[");
      out.print(k);
      out.write("] = '");
      out.print(Array_price[k]);
      out.write("';\r\n");
}
      out.write("\r\n");
      out.write("var tbody = document.getElementById(\"table_body\");\r\n");
      out.write("for (var n = 0; n < count; n++) {\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar tr = document.createElement('tr');\r\n");
      out.write("\t\r\n");
      out.write("\tvar td_check = document.createElement('td');\r\n");
      out.write("\ttd_check.setAttribute(\"scope\",\"row\");\r\n");
      out.write("\ttd_check.setAttribute(\"style\",\"text-align:center;\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar check_input = document.createElement('input');\r\n");
      out.write("\tcheck_input.setAttribute(\"type\",\"checkbox\");\r\n");
      out.write("\ttd_check.appendChild(check_input);\r\n");
      out.write("\ttr.appendChild(td_check);\r\n");
      out.write("\t\r\n");
      out.write("\tvar td_name = document.createElement('td');\r\n");
      out.write("\ttd_name.setAttribute(\"style\", \"text-align:center;\");\r\n");
      out.write("\tvar cellText1 = document.createTextNode(ary_name[n]);\r\n");
      out.write("\ttd_name.appendChild(cellText1);\r\n");
      out.write("\ttr.appendChild(td_name);\r\n");
      out.write("\r\n");
      out.write("\tvar td_count = document.createElement('td');\r\n");
      out.write("\ttd_count.setAttribute(\"style\", \"text-align:center;\");\r\n");
      out.write("\tvar cellText2 = document.createTextNode(ary_price[n]);\r\n");
      out.write("\ttd_count.appendChild(cellText2);\r\n");
      out.write("\ttr.appendChild(td_count);\r\n");
      out.write("\r\n");
      out.write("\tvar td_bookmark_name = document.createElement('td');\r\n");
      out.write("\ttd_bookmark_name.setAttribute(\"style\", \"text-align:center;\");\r\n");
      out.write("\tvar cellText3 = document.createTextNode(ary_count[n]);\r\n");
      out.write("\ttd_bookmark_name.appendChild(cellText3);\r\n");
      out.write("\ttr.appendChild(td_bookmark_name);\r\n");
      out.write("\r\n");
      out.write("\ttbody.appendChild(tr);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
